### ISSUE TITLE
cant play midi

### ISSUE THREAD

**Issue by deltanedas** [Partmedia/mining-station-14#23]
## Description
any instrument ive tried including musician pda says i dont have fluidsynth
i do have it and it works fine on upstream, maybe missing an upstream fix pr merge?

**Reproduction**
1. get musician pda in ruin
2. cant play it

**Additional context**
using pipewire 0.3.71 on linux 6.1.29

**Comment by Partmedia** [comment]
Thank you for your report. We'll look if there has been a recent change to fluidsynth support that would fix your issue.

**Comment by Partmedia** [comment]
Could you let me know what version of fluidsynth you have installed? Alternatively, let me know if engine version `v0.93.1.0` fixes the issue for you?

**Comment by deltanedas** [comment]
the fluidsynth version shouldnt matter, updating engine will prob fix ill test in a sec

**Comment by deltanedas** [comment]
ok i figured out why

something upstream changed so that it no longer checks for fluidsynth in <launcher>/bin/loader so you dont need to make a symlink
ms needs this change merged or you can just ln -s
