### ISSUE TITLE
caveins can happen with no warning or delay

### ISSUE THREAD

**Issue by deltanedas** [Partmedia/mining-station-14#24]
## Description
mine a rock and it instantly crits you with no warning or delay because yes

**Comment by Partmedia** [comment]
Thanks for the report.

You should have more than 30+ seconds of warning when the rocks above you rumble. Are you sure you didn't see these warnings and the cave in happened immediately? (e.g. are you sure the rocks weren't already about to cave in before you mined them?)

If there's a particular way to reproduce this, let us know so we can find the issue quicker.

**Comment by deltanedas** [comment]
- a few days ago solo or something i mined a rock and at the exact time it then caved in and killed me
- today i mined a rock and ~3 seconds later it caved in and killed me

in both cases there was no popup or sound at all

i havent found reproduction steps but it might happen when the map naturally has unsupported caves it might skip warnings when mining idk
